---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python-learning

resources:
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml

images:
  - name: python-learning-image
    newName: ghcr.io/danmanners/python-learning
    newTag: v0.1.1
